# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainUI.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt, QTimer)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QComboBox, QHBoxLayout,
    QHeaderView, QLCDNumber, QLabel, QLineEdit,
    QListView, QListWidget, QListWidgetItem, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QVBoxLayout,
    QWidget)
import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
import App.configs.icons_rc
from PySide6 import QtGui, QtWidgets, QtCore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1103, 630)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(170, 80, 771, 481))
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setIconSize(QSize(150, 30))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_2 = QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 771, 441))
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.layoutWidget = QWidget(self.tab_6)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(9, 9, 751, 401))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_3 = QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        icon = QIcon()
        icon.addFile(u"./Data/UI_icons/User.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QSize(50, 50))

        self.verticalLayout.addWidget(self.pushButton_3)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")

        self.horizontalLayout_3.addWidget(self.label_4)

        self.listWidget = QListWidget(self.layoutWidget)
        self.listWidget.setObjectName(u"listWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)

        self.horizontalLayout_3.addWidget(self.listWidget)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.lineEdit = QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")

        self.verticalLayout.addWidget(self.lineEdit)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")

        self.horizontalLayout_4.addWidget(self.label_5)

        self.listWidget_2 = QListWidget(self.layoutWidget)
        self.listWidget_2.setObjectName(u"listWidget_2")
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)

        self.horizontalLayout_4.addWidget(self.listWidget_2)


        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.lineEdit_2 = QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")

        self.verticalLayout.addWidget(self.lineEdit_2)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")

        self.horizontalLayout_5.addWidget(self.label_6)

        self.listWidget_3 = QListWidget(self.layoutWidget)
        self.listWidget_3.setObjectName(u"listWidget_3")
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)

        self.horizontalLayout_5.addWidget(self.listWidget_3)


        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.comboBox = QComboBox(self.layoutWidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")

        self.verticalLayout.addWidget(self.comboBox)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_7 = QLabel(self.layoutWidget)
        self.label_7.setObjectName(u"label_7")

        self.horizontalLayout_6.addWidget(self.label_7)

        self.listWidget_4 = QListWidget(self.layoutWidget)
        self.listWidget_4.setObjectName(u"listWidget_4")
        sizePolicy.setHeightForWidth(self.listWidget_4.sizePolicy().hasHeightForWidth())
        self.listWidget_4.setSizePolicy(sizePolicy)

        self.horizontalLayout_6.addWidget(self.listWidget_4)


        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.lineEdit_3 = QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")

        self.verticalLayout.addWidget(self.lineEdit_3)

        self.pushButton_4 = QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName(u"pushButton_4")

        self.verticalLayout.addWidget(self.pushButton_4)

        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.tableWidget = QTableWidget(self.tab_8)
        if (self.tableWidget.columnCount() < 1):
            self.tableWidget.setColumnCount(1)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        if (self.tableWidget.rowCount() < 4):
            self.tableWidget.setRowCount(4)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, __qtablewidgetitem4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 0, 771, 421))
        self.tableWidget.horizontalHeader().setDefaultSectionSize(700)
        self.tableWidget.verticalHeader().setDefaultSectionSize(98)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.label_8 = QLabel(self.tab_7)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(60, 0, 691, 61))
        self.label_8.setStyleSheet(u"font: 700 25pt \"Microsoft YaHei UI\";")
        self.pushButton_5 = QPushButton(self.tab_7)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(320, 310, 121, 51))
        self.layoutWidget1 = QWidget(self.tab_7)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(60, 70, 641, 221))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.label_13 = QLabel(self.layoutWidget1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_8.addWidget(self.label_13)

        self.label_14 = QLabel(self.layoutWidget1)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_8.addWidget(self.label_14)


        self.verticalLayout_3.addLayout(self.horizontalLayout_8)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.comboBox_2 = QComboBox(self.layoutWidget1)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")

        self.horizontalLayout_7.addWidget(self.comboBox_2)

        self.comboBox_3 = QComboBox(self.layoutWidget1)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")

        self.horizontalLayout_7.addWidget(self.comboBox_3)


        self.verticalLayout_3.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.comboBox_4 = QComboBox(self.layoutWidget1)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")

        self.horizontalLayout_9.addWidget(self.comboBox_4)

        self.comboBox_5 = QComboBox(self.layoutWidget1)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")

        self.horizontalLayout_9.addWidget(self.comboBox_5)


        self.verticalLayout_3.addLayout(self.horizontalLayout_9)

        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.comboBox_6 = QComboBox(self.layoutWidget1)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")

        self.horizontalLayout_10.addWidget(self.comboBox_6)

        self.comboBox_7 = QComboBox(self.layoutWidget1)
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")

        self.horizontalLayout_10.addWidget(self.comboBox_7)


        self.verticalLayout_3.addLayout(self.horizontalLayout_10)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.comboBox_8 = QComboBox(self.layoutWidget1)
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setObjectName(u"comboBox_8")

        self.horizontalLayout_11.addWidget(self.comboBox_8)

        self.comboBox_9 = QComboBox(self.layoutWidget1)
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.setObjectName(u"comboBox_9")

        self.horizontalLayout_11.addWidget(self.comboBox_9)


        self.verticalLayout_3.addLayout(self.horizontalLayout_11)

        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.label_9 = QLabel(self.tab_9)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(100, 0, 561, 61))
        self.label_9.setStyleSheet(u"font: 700 25pt \"Microsoft YaHei UI\";")
        self.pushButton_6 = QPushButton(self.tab_9)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(310, 310, 121, 51))
        self.layoutWidget2 = QWidget(self.tab_9)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(50, 80, 641, 211))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.label_15 = QLabel(self.layoutWidget2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_12.addWidget(self.label_15)

        self.label_16 = QLabel(self.layoutWidget2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_12.addWidget(self.label_16)


        self.verticalLayout_4.addLayout(self.horizontalLayout_12)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.comboBox_10 = QComboBox(self.layoutWidget2)
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.setObjectName(u"comboBox_10")

        self.horizontalLayout_13.addWidget(self.comboBox_10)

        self.comboBox_11 = QComboBox(self.layoutWidget2)
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.setObjectName(u"comboBox_11")

        self.horizontalLayout_13.addWidget(self.comboBox_11)


        self.verticalLayout_4.addLayout(self.horizontalLayout_13)

        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.comboBox_12 = QComboBox(self.layoutWidget2)
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.setObjectName(u"comboBox_12")

        self.horizontalLayout_14.addWidget(self.comboBox_12)

        self.comboBox_13 = QComboBox(self.layoutWidget2)
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.setObjectName(u"comboBox_13")

        self.horizontalLayout_14.addWidget(self.comboBox_13)


        self.verticalLayout_4.addLayout(self.horizontalLayout_14)

        self.horizontalLayout_15 = QHBoxLayout()
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.comboBox_14 = QComboBox(self.layoutWidget2)
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.setObjectName(u"comboBox_14")

        self.horizontalLayout_15.addWidget(self.comboBox_14)

        self.comboBox_15 = QComboBox(self.layoutWidget2)
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.setObjectName(u"comboBox_15")

        self.horizontalLayout_15.addWidget(self.comboBox_15)


        self.verticalLayout_4.addLayout(self.horizontalLayout_15)

        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.comboBox_16 = QComboBox(self.layoutWidget2)
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.setObjectName(u"comboBox_16")

        self.horizontalLayout_16.addWidget(self.comboBox_16)

        self.comboBox_17 = QComboBox(self.layoutWidget2)
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.setObjectName(u"comboBox_17")

        self.horizontalLayout_16.addWidget(self.comboBox_17)


        self.verticalLayout_4.addLayout(self.horizontalLayout_16)

        self.tabWidget_2.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_2, icon, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget_3 = QTabWidget(self.tab_3)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 0, 771, 441))
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.label_10 = QLabel(self.tab_10)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(520, 50, 231, 141))
        self.layoutWidget3 = QWidget(self.tab_10)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(30, 20, 471, 371))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.lineEdit_16 = QLineEdit(self.layoutWidget3)
        self.lineEdit_16.setObjectName(u"lineEdit_16")

        self.horizontalLayout.addWidget(self.lineEdit_16)

        self.pushButton_10 = QPushButton(self.layoutWidget3)
        self.pushButton_10.setObjectName(u"pushButton_10")

        self.horizontalLayout.addWidget(self.pushButton_10)


        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.textEdit = QTextEdit(self.layoutWidget3)
        self.textEdit.setObjectName(u"textEdit")

        self.verticalLayout_2.addWidget(self.textEdit)

        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.pushButton_7 = QPushButton(self.tab_11)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(80, 200, 190, 50))
        self.lcdNumber = QLCDNumber(self.tab_11)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(80, 10, 600, 180))        
        self.pushButton_8 = QPushButton(self.tab_11)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(285, 200, 190, 50))
        self.pushButton_9 = QPushButton(self.tab_11)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(490, 200, 190, 50))
        self.tabWidget_3.addTab(self.tab_11, "")
        icon1 = QIcon()
        icon1.addFile(u"./Data/UI_icons/Sport.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon1, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget_4 = QTabWidget(self.tab_4)
        self.tabWidget_4.setObjectName(u"tabWidget_4")
        self.tabWidget_4.setGeometry(QRect(0, 0, 771, 441))
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.pushButton_11 = QPushButton(self.tab_12)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(10, 10, 141, 31))
        self.layoutWidget4 = QWidget(self.tab_12)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(20, 60, 741, 211))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_11 = QLabel(self.layoutWidget4)
        self.label_11.setObjectName(u"label_11")

        self.horizontalLayout_2.addWidget(self.label_11)

        self.label_12 = QLabel(self.layoutWidget4)
        self.label_12.setObjectName(u"label_12")

        self.horizontalLayout_2.addWidget(self.label_12)

        self.pushButton_12 = QPushButton(self.tab_12)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(20, 280, 151, 61))
        self.listView = QListView(self.tab_12)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(390, 280, 371, 131))
        self.comboBox_18 = QComboBox(self.tab_12)
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.setObjectName(u"comboBox_18")
        self.comboBox_18.setGeometry(QRect(370, 20, 316, 21))
        self.label_17 = QLabel(self.tab_12)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(190, 20, 181, 20))
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget_4.addTab(self.tab_12, "")
        icon2 = QIcon()
        icon2.addFile(u"./Data/UI_icons/Diet.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon2, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tab.setMouseTracking(True)
        self.tab.setStyleSheet(u"")
        self.calendarWidget = QCalendarWidget(self.tab)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(0, 0, 761, 441))
        self.calendarWidget.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        icon3 = QIcon()
        icon3.addFile(u"./Data/UI_icons/Calendar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tab, icon3, "")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(90, 40, 851, 521))
        self.label.setAutoFillBackground(False)
        self.label.setPixmap(QPixmap(u"./Data/UI_icons/FitYou_UI_Background.png"))
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(90, 40, 81, 81))
        self.label_2.setStyleSheet(u"QLabel{\n"
"background-color: transparent;\n"
"}")
        self.label_2.setPixmap(QPixmap(u"./Data/UI_icons/New_icon.png"))
        self.label_2.setScaledContents(True)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(910, 50, 31, 31))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setTabletTracking(True)
        self.pushButton.setStyleSheet(u"QPushButton{\n"
"		background-color:transparent\n"
"}\n"
"QPushButton:hover{\n"
"		background-color:#ff0000;\n"
"		color: white\n"
"}")
        icon4 = QIcon()
        icon4.addFile(u"./Data/UI_icons/Close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setCheckable(False)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(880, 50, 31, 31))
        self.pushButton_2.setStyleSheet(u"QPushButton{\n"
"		background-color:transparent\n"
"}\n"
"QPushButton:hover{\n"
"		background-color:#d9d9d9;\n"
"		color: white\n"
"}")
        icon5 = QIcon()
        icon5.addFile(u"./Data/UI_icons/Minimize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(180, 50, 121, 31))
        self.label_3.setAutoFillBackground(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.raise_()
        self.tabWidget.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(3)
        self.pushButton_3.setDefault(True)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_3.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Ages", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Sex", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Male", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Female", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"/", None))

        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Weight", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Save All", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Personal_Information", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"To Do List", None));
        ___qtablewidgetitem1 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Morning", None));
        ___qtablewidgetitem2 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Noon", None));
        ___qtablewidgetitem3 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Afternoon", None));
        ___qtablewidgetitem4 = self.tableWidget.verticalHeaderItem(3)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Night", None));
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Fitness_Plan", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Today's Fitness Record!!! Keep Going!!!", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Save All", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Sports", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Tennis", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Badminton", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"Swimming", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("MainWindow", u"Treadmill", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("MainWindow", u"Squat", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("MainWindow", u"Leg Curls", None))
        self.comboBox_2.setItemText(7, QCoreApplication.translate("MainWindow", u"Lateral Raise", None))
        self.comboBox_2.setItemText(8, QCoreApplication.translate("MainWindow", u"Biceps Curl", None))
        self.comboBox_2.setItemText(9, QCoreApplication.translate("MainWindow", u"Abdominal Crunch", None))
        self.comboBox_2.setItemText(10, QCoreApplication.translate("MainWindow", u"Sit-ups", None))
        self.comboBox_2.setItemText(11, QCoreApplication.translate("MainWindow", u"Parallels Bars Arm Support", None))
        self.comboBox_2.setItemText(12, QCoreApplication.translate("MainWindow", u"Deadlifts", None))
        self.comboBox_2.setItemText(13, QCoreApplication.translate("MainWindow", u"Push-ups", None))
        self.comboBox_2.setItemText(14, QCoreApplication.translate("MainWindow", u"Jogging", None))
        self.comboBox_2.setItemText(15, QCoreApplication.translate("MainWindow", u"Brisk Walking", None))
        self.comboBox_2.setItemText(16, QCoreApplication.translate("MainWindow", u"Cycling", None))
        self.comboBox_2.setItemText(17, QCoreApplication.translate("MainWindow", u"Skipping", None))
        self.comboBox_2.setItemText(18, QCoreApplication.translate("MainWindow", u"Aerobics", None))
        self.comboBox_2.setItemText(19, QCoreApplication.translate("MainWindow", u"Yoga", None))
        self.comboBox_2.setItemText(20, QCoreApplication.translate("MainWindow", u"Pilates", None))
        self.comboBox_2.setItemText(21, QCoreApplication.translate("MainWindow", u"HIIT", None))
        self.comboBox_2.setItemText(22, QCoreApplication.translate("MainWindow", u"Rowing Machine", None))
        self.comboBox_2.setItemText(23, QCoreApplication.translate("MainWindow", u"Bobbi Jump", None))
        self.comboBox_2.setItemText(24, QCoreApplication.translate("MainWindow", u"Basketball", None))
        self.comboBox_2.setItemText(25, QCoreApplication.translate("MainWindow", u"Elliptical Training", None))

        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"5min", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", u"10min", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("MainWindow", u"15min", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("MainWindow", u"20min", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("MainWindow", u"25min", None))
        self.comboBox_3.setItemText(6, QCoreApplication.translate("MainWindow", u"30min", None))
        self.comboBox_3.setItemText(7, QCoreApplication.translate("MainWindow", u"35min", None))
        self.comboBox_3.setItemText(8, QCoreApplication.translate("MainWindow", u"40min", None))
        self.comboBox_3.setItemText(9, QCoreApplication.translate("MainWindow", u"45min", None))
        self.comboBox_3.setItemText(10, QCoreApplication.translate("MainWindow", u"50min", None))
        self.comboBox_3.setItemText(11, QCoreApplication.translate("MainWindow", u"55min", None))
        self.comboBox_3.setItemText(12, QCoreApplication.translate("MainWindow", u"60min", None))
        self.comboBox_3.setItemText(13, QCoreApplication.translate("MainWindow", u"1h15min", None))
        self.comboBox_3.setItemText(14, QCoreApplication.translate("MainWindow", u"1h30min", None))
        self.comboBox_3.setItemText(15, QCoreApplication.translate("MainWindow", u"1h45min", None))
        self.comboBox_3.setItemText(16, QCoreApplication.translate("MainWindow", u"2h", None))

        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"Tennis", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"Badminton", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("MainWindow", u"Swimming", None))
        self.comboBox_4.setItemText(4, QCoreApplication.translate("MainWindow", u"Treadmill", None))
        self.comboBox_4.setItemText(5, QCoreApplication.translate("MainWindow", u"Squat", None))
        self.comboBox_4.setItemText(6, QCoreApplication.translate("MainWindow", u"Leg Curls", None))
        self.comboBox_4.setItemText(7, QCoreApplication.translate("MainWindow", u"Lateral Raise", None))
        self.comboBox_4.setItemText(8, QCoreApplication.translate("MainWindow", u"Biceps Curl", None))
        self.comboBox_4.setItemText(9, QCoreApplication.translate("MainWindow", u"Abdominal Crunch", None))
        self.comboBox_4.setItemText(10, QCoreApplication.translate("MainWindow", u"Sit-ups", None))
        self.comboBox_4.setItemText(11, QCoreApplication.translate("MainWindow", u"Parallels Bars Arm Support", None))
        self.comboBox_4.setItemText(12, QCoreApplication.translate("MainWindow", u"Deadlifts", None))
        self.comboBox_4.setItemText(13, QCoreApplication.translate("MainWindow", u"Push-ups", None))
        self.comboBox_4.setItemText(14, QCoreApplication.translate("MainWindow", u"Jogging", None))
        self.comboBox_4.setItemText(15, QCoreApplication.translate("MainWindow", u"Brisk Walking", None))
        self.comboBox_4.setItemText(16, QCoreApplication.translate("MainWindow", u"Cycling", None))
        self.comboBox_4.setItemText(17, QCoreApplication.translate("MainWindow", u"Skipping", None))
        self.comboBox_4.setItemText(18, QCoreApplication.translate("MainWindow", u"Aerobics", None))
        self.comboBox_4.setItemText(19, QCoreApplication.translate("MainWindow", u"Yoga", None))
        self.comboBox_4.setItemText(20, QCoreApplication.translate("MainWindow", u"Pilates", None))
        self.comboBox_4.setItemText(21, QCoreApplication.translate("MainWindow", u"HIIT", None))
        self.comboBox_4.setItemText(22, QCoreApplication.translate("MainWindow", u"Rowing Machine", None))
        self.comboBox_4.setItemText(23, QCoreApplication.translate("MainWindow", u"Bobbi Jump", None))
        self.comboBox_4.setItemText(24, QCoreApplication.translate("MainWindow", u"Basketball", None))
        self.comboBox_4.setItemText(25, QCoreApplication.translate("MainWindow", u"Elliptical Training", None))

        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.setItemText(1, QCoreApplication.translate("MainWindow", u"5min", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("MainWindow", u"10min", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("MainWindow", u"15min", None))
        self.comboBox_5.setItemText(4, QCoreApplication.translate("MainWindow", u"20min", None))
        self.comboBox_5.setItemText(5, QCoreApplication.translate("MainWindow", u"25min", None))
        self.comboBox_5.setItemText(6, QCoreApplication.translate("MainWindow", u"30min", None))
        self.comboBox_5.setItemText(7, QCoreApplication.translate("MainWindow", u"35min", None))
        self.comboBox_5.setItemText(8, QCoreApplication.translate("MainWindow", u"40min", None))
        self.comboBox_5.setItemText(9, QCoreApplication.translate("MainWindow", u"45min", None))
        self.comboBox_5.setItemText(10, QCoreApplication.translate("MainWindow", u"50min", None))
        self.comboBox_5.setItemText(11, QCoreApplication.translate("MainWindow", u"55min", None))
        self.comboBox_5.setItemText(12, QCoreApplication.translate("MainWindow", u"60min", None))
        self.comboBox_5.setItemText(13, QCoreApplication.translate("MainWindow", u"1h15min", None))
        self.comboBox_5.setItemText(14, QCoreApplication.translate("MainWindow", u"1h30min", None))
        self.comboBox_5.setItemText(15, QCoreApplication.translate("MainWindow", u"1h45min", None))
        self.comboBox_5.setItemText(16, QCoreApplication.translate("MainWindow", u"2h", None))

        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.setItemText(1, QCoreApplication.translate("MainWindow", u"Tennis", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("MainWindow", u"Badminton", None))
        self.comboBox_6.setItemText(3, QCoreApplication.translate("MainWindow", u"Swimming", None))
        self.comboBox_6.setItemText(4, QCoreApplication.translate("MainWindow", u"Treadmill", None))
        self.comboBox_6.setItemText(5, QCoreApplication.translate("MainWindow", u"Squat", None))
        self.comboBox_6.setItemText(6, QCoreApplication.translate("MainWindow", u"Leg Curls", None))
        self.comboBox_6.setItemText(7, QCoreApplication.translate("MainWindow", u"Lateral Raise", None))
        self.comboBox_6.setItemText(8, QCoreApplication.translate("MainWindow", u"Biceps Curl", None))
        self.comboBox_6.setItemText(9, QCoreApplication.translate("MainWindow", u"Abdominal Crunch", None))
        self.comboBox_6.setItemText(10, QCoreApplication.translate("MainWindow", u"Sit-ups", None))
        self.comboBox_6.setItemText(11, QCoreApplication.translate("MainWindow", u"Parallels Bars Arm Support", None))
        self.comboBox_6.setItemText(12, QCoreApplication.translate("MainWindow", u"Deadlifts", None))
        self.comboBox_6.setItemText(13, QCoreApplication.translate("MainWindow", u"Push-ups", None))
        self.comboBox_6.setItemText(14, QCoreApplication.translate("MainWindow", u"Jogging", None))
        self.comboBox_6.setItemText(15, QCoreApplication.translate("MainWindow", u"Brisk Walking", None))
        self.comboBox_6.setItemText(16, QCoreApplication.translate("MainWindow", u"Cycling", None))
        self.comboBox_6.setItemText(17, QCoreApplication.translate("MainWindow", u"Skipping", None))
        self.comboBox_6.setItemText(18, QCoreApplication.translate("MainWindow", u"Aerobics", None))
        self.comboBox_6.setItemText(19, QCoreApplication.translate("MainWindow", u"Yoga", None))
        self.comboBox_6.setItemText(20, QCoreApplication.translate("MainWindow", u"Pilates", None))
        self.comboBox_6.setItemText(21, QCoreApplication.translate("MainWindow", u"HIIT", None))
        self.comboBox_6.setItemText(22, QCoreApplication.translate("MainWindow", u"Rowing Machine", None))
        self.comboBox_6.setItemText(23, QCoreApplication.translate("MainWindow", u"Bobbi Jump", None))
        self.comboBox_6.setItemText(24, QCoreApplication.translate("MainWindow", u"Basketball", None))
        self.comboBox_6.setItemText(25, QCoreApplication.translate("MainWindow", u"Elliptical Training", None))

        self.comboBox_7.setItemText(0, "")
        self.comboBox_7.setItemText(1, QCoreApplication.translate("MainWindow", u"5min", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("MainWindow", u"10min", None))
        self.comboBox_7.setItemText(3, QCoreApplication.translate("MainWindow", u"15min", None))
        self.comboBox_7.setItemText(4, QCoreApplication.translate("MainWindow", u"20min", None))
        self.comboBox_7.setItemText(5, QCoreApplication.translate("MainWindow", u"25min", None))
        self.comboBox_7.setItemText(6, QCoreApplication.translate("MainWindow", u"30min", None))
        self.comboBox_7.setItemText(7, QCoreApplication.translate("MainWindow", u"35min", None))
        self.comboBox_7.setItemText(8, QCoreApplication.translate("MainWindow", u"40min", None))
        self.comboBox_7.setItemText(9, QCoreApplication.translate("MainWindow", u"45min", None))
        self.comboBox_7.setItemText(10, QCoreApplication.translate("MainWindow", u"50min", None))
        self.comboBox_7.setItemText(11, QCoreApplication.translate("MainWindow", u"55min", None))
        self.comboBox_7.setItemText(12, QCoreApplication.translate("MainWindow", u"60min", None))
        self.comboBox_7.setItemText(13, QCoreApplication.translate("MainWindow", u"1h15min", None))
        self.comboBox_7.setItemText(14, QCoreApplication.translate("MainWindow", u"1h30min", None))
        self.comboBox_7.setItemText(15, QCoreApplication.translate("MainWindow", u"1h45min", None))
        self.comboBox_7.setItemText(16, QCoreApplication.translate("MainWindow", u"2h", None))

        self.comboBox_8.setItemText(0, "")
        self.comboBox_8.setItemText(1, QCoreApplication.translate("MainWindow", u"Tennis", None))
        self.comboBox_8.setItemText(2, QCoreApplication.translate("MainWindow", u"Badminton", None))
        self.comboBox_8.setItemText(3, QCoreApplication.translate("MainWindow", u"Swimming", None))
        self.comboBox_8.setItemText(4, QCoreApplication.translate("MainWindow", u"Treadmill", None))
        self.comboBox_8.setItemText(5, QCoreApplication.translate("MainWindow", u"Squat", None))
        self.comboBox_8.setItemText(6, QCoreApplication.translate("MainWindow", u"Leg Curls", None))
        self.comboBox_8.setItemText(7, QCoreApplication.translate("MainWindow", u"Lateral Raise", None))
        self.comboBox_8.setItemText(8, QCoreApplication.translate("MainWindow", u"Biceps Curl", None))
        self.comboBox_8.setItemText(9, QCoreApplication.translate("MainWindow", u"Abdominal Crunch", None))
        self.comboBox_8.setItemText(10, QCoreApplication.translate("MainWindow", u"Sit-ups", None))
        self.comboBox_8.setItemText(11, QCoreApplication.translate("MainWindow", u"Parallels Bars Arm Support", None))
        self.comboBox_8.setItemText(12, QCoreApplication.translate("MainWindow", u"Deadlifts", None))
        self.comboBox_8.setItemText(13, QCoreApplication.translate("MainWindow", u"Push-ups", None))
        self.comboBox_8.setItemText(14, QCoreApplication.translate("MainWindow", u"Jogging", None))
        self.comboBox_8.setItemText(15, QCoreApplication.translate("MainWindow", u"Brisk Walking", None))
        self.comboBox_8.setItemText(16, QCoreApplication.translate("MainWindow", u"Cycling", None))
        self.comboBox_8.setItemText(17, QCoreApplication.translate("MainWindow", u"Skipping", None))
        self.comboBox_8.setItemText(18, QCoreApplication.translate("MainWindow", u"Aerobics", None))
        self.comboBox_8.setItemText(19, QCoreApplication.translate("MainWindow", u"Yoga", None))
        self.comboBox_8.setItemText(20, QCoreApplication.translate("MainWindow", u"Pilates", None))
        self.comboBox_8.setItemText(21, QCoreApplication.translate("MainWindow", u"HIIT", None))
        self.comboBox_8.setItemText(22, QCoreApplication.translate("MainWindow", u"Rowing Machine", None))
        self.comboBox_8.setItemText(23, QCoreApplication.translate("MainWindow", u"Bobbi Jump", None))
        self.comboBox_8.setItemText(24, QCoreApplication.translate("MainWindow", u"Basketball", None))
        self.comboBox_8.setItemText(25, QCoreApplication.translate("MainWindow", u"Elliptical Training", None))

        self.comboBox_9.setItemText(0, "")
        self.comboBox_9.setItemText(1, QCoreApplication.translate("MainWindow", u"5min", None))
        self.comboBox_9.setItemText(2, QCoreApplication.translate("MainWindow", u"10min", None))
        self.comboBox_9.setItemText(3, QCoreApplication.translate("MainWindow", u"15min", None))
        self.comboBox_9.setItemText(4, QCoreApplication.translate("MainWindow", u"20min", None))
        self.comboBox_9.setItemText(5, QCoreApplication.translate("MainWindow", u"25min", None))
        self.comboBox_9.setItemText(6, QCoreApplication.translate("MainWindow", u"30min", None))
        self.comboBox_9.setItemText(7, QCoreApplication.translate("MainWindow", u"35min", None))
        self.comboBox_9.setItemText(8, QCoreApplication.translate("MainWindow", u"40min", None))
        self.comboBox_9.setItemText(9, QCoreApplication.translate("MainWindow", u"45min", None))
        self.comboBox_9.setItemText(10, QCoreApplication.translate("MainWindow", u"50min", None))
        self.comboBox_9.setItemText(11, QCoreApplication.translate("MainWindow", u"55min", None))
        self.comboBox_9.setItemText(12, QCoreApplication.translate("MainWindow", u"60min", None))
        self.comboBox_9.setItemText(13, QCoreApplication.translate("MainWindow", u"1h15min", None))
        self.comboBox_9.setItemText(14, QCoreApplication.translate("MainWindow", u"1h30min", None))
        self.comboBox_9.setItemText(15, QCoreApplication.translate("MainWindow", u"1h45min", None))
        self.comboBox_9.setItemText(16, QCoreApplication.translate("MainWindow", u"2h", None))

        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Fitness_Record", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Today's Diet Record!!! Hold On!!!", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Save All", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Diet", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Weight", None))
        self.comboBox_10.setItemText(0, "")
        self.comboBox_10.setItemText(1, QCoreApplication.translate("MainWindow", u"Flour", None))
        self.comboBox_10.setItemText(2, QCoreApplication.translate("MainWindow", u"Peas", None))
        self.comboBox_10.setItemText(3, QCoreApplication.translate("MainWindow", u"Chinese Cabbage", None))
        self.comboBox_10.setItemText(4, QCoreApplication.translate("MainWindow", u"Fungus", None))
        self.comboBox_10.setItemText(5, QCoreApplication.translate("MainWindow", u"Kelp", None))
        self.comboBox_10.setItemText(6, QCoreApplication.translate("MainWindow", u"Pumkins", None))
        self.comboBox_10.setItemText(7, QCoreApplication.translate("MainWindow", u"Apples", None))
        self.comboBox_10.setItemText(8, QCoreApplication.translate("MainWindow", u"Cherries", None))
        self.comboBox_10.setItemText(9, QCoreApplication.translate("MainWindow", u"Bananas", None))
        self.comboBox_10.setItemText(10, QCoreApplication.translate("MainWindow", u"Almonds", None))
        self.comboBox_10.setItemText(11, QCoreApplication.translate("MainWindow", u"Beef", None))
        self.comboBox_10.setItemText(12, QCoreApplication.translate("MainWindow", u"Pork Liver", None))
        self.comboBox_10.setItemText(13, QCoreApplication.translate("MainWindow", u"Pork", None))
        self.comboBox_10.setItemText(14, QCoreApplication.translate("MainWindow", u"Milk", None))
        self.comboBox_10.setItemText(15, QCoreApplication.translate("MainWindow", u"Eggs", None))
        self.comboBox_10.setItemText(16, QCoreApplication.translate("MainWindow", u"Potato", None))
        self.comboBox_10.setItemText(17, QCoreApplication.translate("MainWindow", u"Tomato", None))
        self.comboBox_10.setItemText(18, QCoreApplication.translate("MainWindow", u"Broccoli", None))
        self.comboBox_10.setItemText(19, QCoreApplication.translate("MainWindow", u"Chicken Breast", None))
        self.comboBox_10.setItemText(20, QCoreApplication.translate("MainWindow", u"Cods", None))
        self.comboBox_10.setItemText(21, QCoreApplication.translate("MainWindow", u"Pork Loin", None))
        self.comboBox_10.setItemText(22, QCoreApplication.translate("MainWindow", u"Salmon", None))
        self.comboBox_10.setItemText(23, QCoreApplication.translate("MainWindow", u"Lamb Shank", None))
        self.comboBox_10.setItemText(24, QCoreApplication.translate("MainWindow", u"Brown Rice", None))
        self.comboBox_10.setItemText(25, QCoreApplication.translate("MainWindow", u"Black Beans", None))
        self.comboBox_10.setItemText(26, QCoreApplication.translate("MainWindow", u"Sweet Potato", None))
        self.comboBox_10.setItemText(27, QCoreApplication.translate("MainWindow", u"Soba Noodles", None))
        self.comboBox_10.setItemText(28, QCoreApplication.translate("MainWindow", u"Carrot", None))
        self.comboBox_10.setItemText(29, QCoreApplication.translate("MainWindow", u"Kale", None))
        self.comboBox_10.setItemText(30, QCoreApplication.translate("MainWindow", u"Spinach", None))

        self.comboBox_11.setItemText(0, "")
        self.comboBox_11.setItemText(1, QCoreApplication.translate("MainWindow", u"5g", None))
        self.comboBox_11.setItemText(2, QCoreApplication.translate("MainWindow", u"10g", None))
        self.comboBox_11.setItemText(3, QCoreApplication.translate("MainWindow", u"15g", None))
        self.comboBox_11.setItemText(4, QCoreApplication.translate("MainWindow", u"20g", None))
        self.comboBox_11.setItemText(5, QCoreApplication.translate("MainWindow", u"25g", None))
        self.comboBox_11.setItemText(6, QCoreApplication.translate("MainWindow", u"30g", None))
        self.comboBox_11.setItemText(7, QCoreApplication.translate("MainWindow", u"50g", None))
        self.comboBox_11.setItemText(8, QCoreApplication.translate("MainWindow", u"100g", None))
        self.comboBox_11.setItemText(9, QCoreApplication.translate("MainWindow", u"200g", None))

        self.comboBox_12.setItemText(0, "")
        self.comboBox_12.setItemText(1, QCoreApplication.translate("MainWindow", u"Flour", None))
        self.comboBox_12.setItemText(2, QCoreApplication.translate("MainWindow", u"Peas", None))
        self.comboBox_12.setItemText(3, QCoreApplication.translate("MainWindow", u"Chinese Cabbage", None))
        self.comboBox_12.setItemText(4, QCoreApplication.translate("MainWindow", u"Fungus", None))
        self.comboBox_12.setItemText(5, QCoreApplication.translate("MainWindow", u"Kelp", None))
        self.comboBox_12.setItemText(6, QCoreApplication.translate("MainWindow", u"Pumkins", None))
        self.comboBox_12.setItemText(7, QCoreApplication.translate("MainWindow", u"Apples", None))
        self.comboBox_12.setItemText(8, QCoreApplication.translate("MainWindow", u"Cherries", None))
        self.comboBox_12.setItemText(9, QCoreApplication.translate("MainWindow", u"Bananas", None))
        self.comboBox_12.setItemText(10, QCoreApplication.translate("MainWindow", u"Almonds", None))
        self.comboBox_12.setItemText(11, QCoreApplication.translate("MainWindow", u"Beef", None))
        self.comboBox_12.setItemText(12, QCoreApplication.translate("MainWindow", u"Pork Liver", None))
        self.comboBox_12.setItemText(13, QCoreApplication.translate("MainWindow", u"Pork", None))
        self.comboBox_12.setItemText(14, QCoreApplication.translate("MainWindow", u"Milk", None))
        self.comboBox_12.setItemText(15, QCoreApplication.translate("MainWindow", u"Eggs", None))
        self.comboBox_12.setItemText(16, QCoreApplication.translate("MainWindow", u"Potato", None))
        self.comboBox_12.setItemText(17, QCoreApplication.translate("MainWindow", u"Tomato", None))
        self.comboBox_12.setItemText(18, QCoreApplication.translate("MainWindow", u"Broccoli", None))
        self.comboBox_12.setItemText(19, QCoreApplication.translate("MainWindow", u"Chicken Breast", None))
        self.comboBox_12.setItemText(20, QCoreApplication.translate("MainWindow", u"Cods", None))
        self.comboBox_12.setItemText(21, QCoreApplication.translate("MainWindow", u"Pork Loin", None))
        self.comboBox_12.setItemText(22, QCoreApplication.translate("MainWindow", u"Salmon", None))
        self.comboBox_12.setItemText(23, QCoreApplication.translate("MainWindow", u"Lamb Shank", None))
        self.comboBox_12.setItemText(24, QCoreApplication.translate("MainWindow", u"Brown Rice", None))
        self.comboBox_12.setItemText(25, QCoreApplication.translate("MainWindow", u"Black Beans", None))
        self.comboBox_12.setItemText(26, QCoreApplication.translate("MainWindow", u"Sweet Potato", None))
        self.comboBox_12.setItemText(27, QCoreApplication.translate("MainWindow", u"Soba Noodles", None))
        self.comboBox_12.setItemText(28, QCoreApplication.translate("MainWindow", u"Carrot", None))
        self.comboBox_12.setItemText(29, QCoreApplication.translate("MainWindow", u"Kale", None))
        self.comboBox_12.setItemText(30, QCoreApplication.translate("MainWindow", u"Spinach", None))

        self.comboBox_13.setItemText(0, "")
        self.comboBox_13.setItemText(1, QCoreApplication.translate("MainWindow", u"5g", None))
        self.comboBox_13.setItemText(2, QCoreApplication.translate("MainWindow", u"10g", None))
        self.comboBox_13.setItemText(3, QCoreApplication.translate("MainWindow", u"15g", None))
        self.comboBox_13.setItemText(4, QCoreApplication.translate("MainWindow", u"20g", None))
        self.comboBox_13.setItemText(5, QCoreApplication.translate("MainWindow", u"25g", None))
        self.comboBox_13.setItemText(6, QCoreApplication.translate("MainWindow", u"30g", None))
        self.comboBox_13.setItemText(7, QCoreApplication.translate("MainWindow", u"50g", None))
        self.comboBox_13.setItemText(8, QCoreApplication.translate("MainWindow", u"100g", None))
        self.comboBox_13.setItemText(9, QCoreApplication.translate("MainWindow", u"200g", None))

        self.comboBox_14.setItemText(0, "")
        self.comboBox_14.setItemText(1, QCoreApplication.translate("MainWindow", u"Flour", None))
        self.comboBox_14.setItemText(2, QCoreApplication.translate("MainWindow", u"Peas", None))
        self.comboBox_14.setItemText(3, QCoreApplication.translate("MainWindow", u"Chinese Cabbage", None))
        self.comboBox_14.setItemText(4, QCoreApplication.translate("MainWindow", u"Fungus", None))
        self.comboBox_14.setItemText(5, QCoreApplication.translate("MainWindow", u"Kelp", None))
        self.comboBox_14.setItemText(6, QCoreApplication.translate("MainWindow", u"Pumkins", None))
        self.comboBox_14.setItemText(7, QCoreApplication.translate("MainWindow", u"Apples", None))
        self.comboBox_14.setItemText(8, QCoreApplication.translate("MainWindow", u"Cherries", None))
        self.comboBox_14.setItemText(9, QCoreApplication.translate("MainWindow", u"Bananas", None))
        self.comboBox_14.setItemText(10, QCoreApplication.translate("MainWindow", u"Almonds", None))
        self.comboBox_14.setItemText(11, QCoreApplication.translate("MainWindow", u"Beef", None))
        self.comboBox_14.setItemText(12, QCoreApplication.translate("MainWindow", u"Pork Liver", None))
        self.comboBox_14.setItemText(13, QCoreApplication.translate("MainWindow", u"Pork", None))
        self.comboBox_14.setItemText(14, QCoreApplication.translate("MainWindow", u"Milk", None))
        self.comboBox_14.setItemText(15, QCoreApplication.translate("MainWindow", u"Eggs", None))
        self.comboBox_14.setItemText(16, QCoreApplication.translate("MainWindow", u"Potato", None))
        self.comboBox_14.setItemText(17, QCoreApplication.translate("MainWindow", u"Tomato", None))
        self.comboBox_14.setItemText(18, QCoreApplication.translate("MainWindow", u"Broccoli", None))
        self.comboBox_14.setItemText(19, QCoreApplication.translate("MainWindow", u"Chicken Breast", None))
        self.comboBox_14.setItemText(20, QCoreApplication.translate("MainWindow", u"Cods", None))
        self.comboBox_14.setItemText(21, QCoreApplication.translate("MainWindow", u"Pork Loin", None))
        self.comboBox_14.setItemText(22, QCoreApplication.translate("MainWindow", u"Salmon", None))
        self.comboBox_14.setItemText(23, QCoreApplication.translate("MainWindow", u"Lamb Shank", None))
        self.comboBox_14.setItemText(24, QCoreApplication.translate("MainWindow", u"Brown Rice", None))
        self.comboBox_14.setItemText(25, QCoreApplication.translate("MainWindow", u"Black Beans", None))
        self.comboBox_14.setItemText(26, QCoreApplication.translate("MainWindow", u"Sweet Potato", None))
        self.comboBox_14.setItemText(27, QCoreApplication.translate("MainWindow", u"Soba Noodles", None))
        self.comboBox_14.setItemText(28, QCoreApplication.translate("MainWindow", u"Carrot", None))
        self.comboBox_14.setItemText(29, QCoreApplication.translate("MainWindow", u"Kale", None))
        self.comboBox_14.setItemText(30, QCoreApplication.translate("MainWindow", u"Spinach", None))

        self.comboBox_15.setItemText(0, "")
        self.comboBox_15.setItemText(1, QCoreApplication.translate("MainWindow", u"5g", None))
        self.comboBox_15.setItemText(2, QCoreApplication.translate("MainWindow", u"10g", None))
        self.comboBox_15.setItemText(3, QCoreApplication.translate("MainWindow", u"15g", None))
        self.comboBox_15.setItemText(4, QCoreApplication.translate("MainWindow", u"20g", None))
        self.comboBox_15.setItemText(5, QCoreApplication.translate("MainWindow", u"25g", None))
        self.comboBox_15.setItemText(6, QCoreApplication.translate("MainWindow", u"30g", None))
        self.comboBox_15.setItemText(7, QCoreApplication.translate("MainWindow", u"50g", None))
        self.comboBox_15.setItemText(8, QCoreApplication.translate("MainWindow", u"100g", None))
        self.comboBox_15.setItemText(9, QCoreApplication.translate("MainWindow", u"200g", None))

        self.comboBox_16.setItemText(0, "")
        self.comboBox_16.setItemText(1, QCoreApplication.translate("MainWindow", u"Flour", None))
        self.comboBox_16.setItemText(2, QCoreApplication.translate("MainWindow", u"Peas", None))
        self.comboBox_16.setItemText(3, QCoreApplication.translate("MainWindow", u"Chinese Cabbage", None))
        self.comboBox_16.setItemText(4, QCoreApplication.translate("MainWindow", u"Fungus", None))
        self.comboBox_16.setItemText(5, QCoreApplication.translate("MainWindow", u"Kelp", None))
        self.comboBox_16.setItemText(6, QCoreApplication.translate("MainWindow", u"Pumkins", None))
        self.comboBox_16.setItemText(7, QCoreApplication.translate("MainWindow", u"Apples", None))
        self.comboBox_16.setItemText(8, QCoreApplication.translate("MainWindow", u"Cherries", None))
        self.comboBox_16.setItemText(9, QCoreApplication.translate("MainWindow", u"Bananas", None))
        self.comboBox_16.setItemText(10, QCoreApplication.translate("MainWindow", u"Almonds", None))
        self.comboBox_16.setItemText(11, QCoreApplication.translate("MainWindow", u"Beef", None))
        self.comboBox_16.setItemText(12, QCoreApplication.translate("MainWindow", u"Pork Liver", None))
        self.comboBox_16.setItemText(13, QCoreApplication.translate("MainWindow", u"Pork", None))
        self.comboBox_16.setItemText(14, QCoreApplication.translate("MainWindow", u"Milk", None))
        self.comboBox_16.setItemText(15, QCoreApplication.translate("MainWindow", u"Eggs", None))
        self.comboBox_16.setItemText(16, QCoreApplication.translate("MainWindow", u"Potato", None))
        self.comboBox_16.setItemText(17, QCoreApplication.translate("MainWindow", u"Tomato", None))
        self.comboBox_16.setItemText(18, QCoreApplication.translate("MainWindow", u"Broccoli", None))
        self.comboBox_16.setItemText(19, QCoreApplication.translate("MainWindow", u"Chicken Breast", None))
        self.comboBox_16.setItemText(20, QCoreApplication.translate("MainWindow", u"Cods", None))
        self.comboBox_16.setItemText(21, QCoreApplication.translate("MainWindow", u"Pork Loin", None))
        self.comboBox_16.setItemText(22, QCoreApplication.translate("MainWindow", u"Salmon", None))
        self.comboBox_16.setItemText(23, QCoreApplication.translate("MainWindow", u"Lamb Shank", None))
        self.comboBox_16.setItemText(24, QCoreApplication.translate("MainWindow", u"Brown Rice", None))
        self.comboBox_16.setItemText(25, QCoreApplication.translate("MainWindow", u"Black Beans", None))
        self.comboBox_16.setItemText(26, QCoreApplication.translate("MainWindow", u"Sweet Potato", None))
        self.comboBox_16.setItemText(27, QCoreApplication.translate("MainWindow", u"Soba Noodles", None))
        self.comboBox_16.setItemText(28, QCoreApplication.translate("MainWindow", u"Carrot", None))
        self.comboBox_16.setItemText(29, QCoreApplication.translate("MainWindow", u"Kale", None))
        self.comboBox_16.setItemText(30, QCoreApplication.translate("MainWindow", u"Spinach", None))

        self.comboBox_17.setItemText(0, "")
        self.comboBox_17.setItemText(1, QCoreApplication.translate("MainWindow", u"5g", None))
        self.comboBox_17.setItemText(2, QCoreApplication.translate("MainWindow", u"10g", None))
        self.comboBox_17.setItemText(3, QCoreApplication.translate("MainWindow", u"15g", None))
        self.comboBox_17.setItemText(4, QCoreApplication.translate("MainWindow", u"20g", None))
        self.comboBox_17.setItemText(5, QCoreApplication.translate("MainWindow", u"25g", None))
        self.comboBox_17.setItemText(6, QCoreApplication.translate("MainWindow", u"30g", None))
        self.comboBox_17.setItemText(7, QCoreApplication.translate("MainWindow", u"50g", None))
        self.comboBox_17.setItemText(8, QCoreApplication.translate("MainWindow", u"100g", None))
        self.comboBox_17.setItemText(9, QCoreApplication.translate("MainWindow", u"200g", None))

        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Diet_Record", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), "")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Picture", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Search", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"Timer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), "")
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Upload Your Food", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"The food you uploaded ", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"The food's information", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Identify", None))
        self.comboBox_18.setItemText(0, "")
        self.comboBox_18.setItemText(1, QCoreApplication.translate("MainWindow", u"Flour", None))
        self.comboBox_18.setItemText(2, QCoreApplication.translate("MainWindow", u"Peas", None))
        self.comboBox_18.setItemText(3, QCoreApplication.translate("MainWindow", u"Chinese Cabbage", None))
        self.comboBox_18.setItemText(4, QCoreApplication.translate("MainWindow", u"Fungus", None))
        self.comboBox_18.setItemText(5, QCoreApplication.translate("MainWindow", u"Kelp", None))
        self.comboBox_18.setItemText(6, QCoreApplication.translate("MainWindow", u"Pumkins", None))
        self.comboBox_18.setItemText(7, QCoreApplication.translate("MainWindow", u"Apples", None))
        self.comboBox_18.setItemText(8, QCoreApplication.translate("MainWindow", u"Cherries", None))
        self.comboBox_18.setItemText(9, QCoreApplication.translate("MainWindow", u"Bananas", None))
        self.comboBox_18.setItemText(10, QCoreApplication.translate("MainWindow", u"Almonds", None))
        self.comboBox_18.setItemText(11, QCoreApplication.translate("MainWindow", u"Beef", None))
        self.comboBox_18.setItemText(12, QCoreApplication.translate("MainWindow", u"Pork Liver", None))
        self.comboBox_18.setItemText(13, QCoreApplication.translate("MainWindow", u"Pork", None))
        self.comboBox_18.setItemText(14, QCoreApplication.translate("MainWindow", u"Milk", None))
        self.comboBox_18.setItemText(15, QCoreApplication.translate("MainWindow", u"Eggs", None))
        self.comboBox_18.setItemText(16, QCoreApplication.translate("MainWindow", u"Potato", None))
        self.comboBox_18.setItemText(17, QCoreApplication.translate("MainWindow", u"Tomato", None))
        self.comboBox_18.setItemText(18, QCoreApplication.translate("MainWindow", u"Broccoli", None))
        self.comboBox_18.setItemText(19, QCoreApplication.translate("MainWindow", u"Chicken Breast", None))
        self.comboBox_18.setItemText(20, QCoreApplication.translate("MainWindow", u"Cods", None))
        self.comboBox_18.setItemText(21, QCoreApplication.translate("MainWindow", u"Pork Loin", None))
        self.comboBox_18.setItemText(22, QCoreApplication.translate("MainWindow", u"Salmon", None))
        self.comboBox_18.setItemText(23, QCoreApplication.translate("MainWindow", u"Lamb Shank", None))
        self.comboBox_18.setItemText(24, QCoreApplication.translate("MainWindow", u"Brown Rice", None))
        self.comboBox_18.setItemText(25, QCoreApplication.translate("MainWindow", u"Black Beans", None))
        self.comboBox_18.setItemText(26, QCoreApplication.translate("MainWindow", u"Sweet Potato", None))
        self.comboBox_18.setItemText(27, QCoreApplication.translate("MainWindow", u"Soba Noodles", None))
        self.comboBox_18.setItemText(28, QCoreApplication.translate("MainWindow", u"Carrot", None))
        self.comboBox_18.setItemText(29, QCoreApplication.translate("MainWindow", u"Kale", None))
        self.comboBox_18.setItemText(30, QCoreApplication.translate("MainWindow", u"Spinach", None))

        self.label_17.setText(QCoreApplication.translate("MainWindow", u"You can choose your food!", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"Upload_Food", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), "")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), "")
        self.label.setText("")
        self.label_2.setText("")
        self.pushButton.setText("")
        self.pushButton_2.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700; color:#aaaaff;\">Welcome to FitYou.</span></p></body></html>", None))
    # retranslateUi


# if __name__ == '__main__':
#     app = QtWidgets.QApplication(sys.argv)
#     window = Ui_MainWindow()
#     window.show()
#     sys.exit(app.exec())